 - hosts: webservers
   gather_facts: no
   vars_files:
     - ../vars.yml

   tasks:
     - name: clone project from gitlab
       ansible.builtin.git:
         repo: git@git.dns-shop.ru:the-chosen-ones/despair.git
         dest: /var/www/despair
         key_file: /home/grevtsevalex/.ssh/id_rsa
         accept_hostkey: yes
         force: yes
       tags: clone

     - name: Change file ownership, group and permissions
       ansible.builtin.file:
         path: /var
         owner: www-data
         group: www-data
         mode: '0775'

     - name: get permission to project
       ansible.builtin.shell: sudo chgrp -R www-data /var/www/despair && sudo chown -R www-data /var/www

     - name: copy site-local.php file
       ansible.builtin.copy:
         src: ../files/site-local.php
         dest: "/var/www/despair/dns/config"

     - name: install php8
       ansible.builtin.apt:
         name: software-properties-common
         state: latest

     - name: install php8
       ansible.builtin.shell: sudo add-apt-repository ppa:ondrej/php
     
     - name: update
       ansible.builtin.shell: sudo apt update
   
     - name: install php fpm and extensions
       ansible.builtin.apt:
         name:
           - php8.0
           - php8.0-fpm
           - composer
           - php8.0-curl
           - php8.0-grpc
           - php8.0-redis
           - php8.0-memcached
           - php8.0-xml
           - php8.0-intl
           - php8.0-dev
           - php8.0-gd
           - php8.0-zip
           - php8.0-mbstring
           - php-pear
           - librdkafka-dev
           - php8.0-xdebug
         state: latest

     - name: remove php 8.1 version
       ansible.builtin.shell: sudo apt-get purge 'php8.1*' &>1

     - name: install rdkafka extension
       ansible.builtin.shell: yes '' | sudo pecl install -f rdkafka &>1

     - name: add rdkafka to php.ini
       ansible.builtin.shell: grep -Fq 'extension=rdkafka.so' /etc/php/8.0/cli/php.ini || echo 'extension=rdkafka.so' >> /etc/php/8.0/cli/php.ini

     - name: add ext-gd to php.ini
       ansible.builtin.shell: grep -Fq 'extension=gd' /etc/php/8.0/cli/php.ini || echo 'extension=gd' >> /etc/php/8.0/cli/php.ini
     
     - name: restart php-fpm
       ansible.builtin.shell: sudo service php8.0-fpm start
     
     - name: upgrade composer to 2 version
       ansible.builtin.shell: bash ../files/composer.sh

     - name: restart nginx
       ansible.builtin.shell: sudo service nginx restart

     - name: add local config files
       ansible.builtin.shell: cd /var/www/despair/common/config && ls $1 | grep example | sed -e "p;s/\.example\./\./" | xargs -n2 mv

     - name: add LocalConfig file
       ansible.builtin.template:
         src: ../files/LocalConfig.php.j2
         dest: "/var/www/despair/common/config/local/LocalConfig.php"
         mode: '0775'

     - name: create .dev file in the root of project
       ansible.builtin.shell: cd /var/www/despair/ && touch .dev

     - name: give 775 to /var/www
       ansible.builtin.shell: sudo chmod -R 775 /var/www

     - name: install node
       ansible.builtin.shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash - 
       tags: node

     - name: install node
       ansible.builtin.shell: sudo apt -y install nodejs
       tags: node

     - name: install npm
       ansible.builtin.apt:
         name: npm
         state: latest
       become: yes
       become_user: "{{ username }}"
           
