 - hosts: webservers
   gather_facts: no

   tasks:
     - name: add hosts
       ansible.builtin.shell: sudo  echo '127.0.0.1  dns.loc backend.dns.loc www.dns.loc restapi.dns.loc webapi.dns.loc'>> /etc/hosts

     - name: install nginx
       ansible.builtin.apt:
         name: nginx
         state: latest

     - name: copy config for dns.loc
       ansible.builtin.copy:
         src: ../files/dns.conf
         dest: "/etc/nginx/sites-available"

     - name: copy config for restapi.dns.loc
       ansible.builtin.copy:
         src: ../files/restapi.conf
         dest: "/etc/nginx/sites-available"

     - name: Create a symbolic link for dns.conf
       ansible.builtin.file:
         src: /etc/nginx/sites-available/dns.conf
         dest: /etc/nginx/sites-enabled/dns.conf
         group: www-data
         state: link
     
     - name: Create a symbolic link for restapi.conf
       ansible.builtin.file:
         src: /etc/nginx/sites-available/restapi.conf
         dest: /etc/nginx/sites-enabled/restapi.conf
         group: www-data
         state: link
