 - hosts: webservers
   gather_facts: no

   tasks:
     - name: add hosts
       ansible.builtin.shell: sudo  echo '127.0.0.1  dns.loc backend.dns.loc www.dns.loc restapi.dns.loc webapi.dns.loc'>> /etc/hosts

     - name: install nginx
       ansible.builtin.apt:
         name: nginx
         state: latest

     - name: copy config for dns.loc
       ansible.builtin.copy:
         src: ../files/dns.conf
         dest: "/etc/nginx/sites-available"

     - name: copy config for restapi.dns.loc
       ansible.builtin.copy:
         src: ../files/restapi.conf
         dest: "/etc/nginx/sites-available"

     - name: Create a symbolic link for dns.conf
       ansible.builtin.file:
         src: /etc/nginx/sites-available/dns.conf
         dest: /etc/nginx/sites-enabled/dns.conf
         group: www-data
         state: link
     
     - name: Create a symbolic link for restapi.conf
       ansible.builtin.file:
         src: /etc/nginx/sites-available/restapi.conf
         dest: /etc/nginx/sites-enabled/restapi.conf
         group: www-data
         state: link

     - name: clone project from github
       ansible.builtin.git:
         repo: git@git.dns-shop.ru:the-chosen-ones/despair.git
         dest: /var/www/despair
         key_file: /home/grevtsevalex/.ssh/id_rsa
         accept_hostkey: yes
         force: yes
       tags: clone

     - name: Change file ownership, group and permissions
       ansible.builtin.file:
         path: /var
         owner: www-data
         group: www-data
         mode: '0775'

     - name: copy site-local.php file
       ansible.builtin.copy:
         src: ../files/site-local.php
         dest: "/var/www/despair/dns/config"

     - name: install php8
       ansible.builtin.apt:
         name: software-properties-common
         state: latest

     - name: install php8
       ansible.builtin.shell: sudo add-apt-repository ppa:ondrej/php
     
     - name: update
       ansible.builtin.shell: sudo apt update
     
     - name: install php fpm and extensions
       ansible.builtin.apt:
         name:
           - php8.0-fpm
           - composer
           - php8.0-curl
           - php8.0-grpc
           - php8.0-redis
           - php8.0-memcached
           - php8.0-xml
           - php8.0-intl
           - php8.0-dev
           - php8.0-gd
           - php8.0-zip
           - php8.0-mbstring
           - php-pear
           - librdkafka-dev
           - php8.0-xdebug
         state: latest

     - name: install rdkafka extension
       ansible.builtin.shell: sudo pecl install rdkafka | echo 0

     - name: add rdkafka to php.ini
       ansible.builtin.shell: echo 'extension=rdkafka.so' >> /etc/php/8.0/cli/php.ini

     - name: add ext-gd to php.ini
       ansible.builtin.shell: echo 'extension=gd' >> /etc/php/8.0/cli/php.ini
     
     - name: restart php-fpm
       ansible.builtin.shell: sudo service php8.0-fpm restart
     
     - name: upgrade composer to 2 version
       ansible.builtin.shell: bash ../files/composer.sh
