 - hosts: webservers
   gather_facts: no

   tasks:
     - name: uninstall nginx
       ansible.builtin.apt:
         name: nginx
         state: absent
       become: yes

     - name: remove config for dns.loc
       ansible.builtin.file:
         path: "/etc/nginx/site-available/dns.conf"
         state: absent
       become: yes

     - name: remove config for restapi.dns.loc
       ansible.builtin.file:
         path: "/etc/nginx/site-available/restapi.conf"
         state: absent
       become: yes
