- hosts: localhost
  gather_facts: no

  tasks:
    - name: remove git
      ansible.builtin.apt:
        name: git
        state: absent
      become:yes

    - name: remove git config file
      ansible.builtin.file:
        src: "files/user/.gitconfig.j2"
        state: absent 
      become: yes
